### ISSUE TITLE
sqlite?

### ISSUE THREAD

**Issue by jrsmith3** [pkienzle/periodictable#13]
I really like the API of this package and I've found the package to be quite useful. However, is there any reason why you didn't put all the data in a database like sqlite?

Thanks for pulling all this data together in a way that's easy to use.

**Comment by pkienzle** [comment]
The main reason is my lack of experience with SQL.  It would probably be a
win for the X-ray data since it is large, and could also benefit the other
tables by removing the parsing step.

The lookup into the energy table for X-rays needs to use interpolation,
possibly on an array of energies.  I don't know if SQL can handle this
directly, or if it is better to load the tables into numpy arrays and let
numpy do it.

**Comment by lmmentel** [comment]
I hope this issue isn't dead yet. First of all, great package! I have similar open source python package called [mendeleev](http://mendeleev.readthedocs.io/en/stable/) that is a python interface around periodic table data stored in a sqlite database. I already collected a lot of [data](http://mendeleev.readthedocs.io/en/stable/data.html) so it might be a good starting point if you are considering moving towards sqlite. The source is hosted in a [bitbucket repo](https://bitbucket.org/lukaszmentel/mendeleev/) if you are interested.

I can help with your schema design and injecting the data into a database since I would also be interested in having access to some of the data you have. Let me know what you think.

**Comment by pkienzle** [comment]
Still interested in principle, but I'm not sure how much benefit there will be.

I want to keep the data in the repo as text.  That way I can show users diffs to see what data has changed between versions (source control doesn't work well with binary blobs). It makes it convenient for getting updates from the original sources if I leave it in the original format.  By building the database as part of the installation process I also remove any database migration issues.

Since I will still have the code to process the original data, there is not much maintenance benefit.  I hope that using sql would lead to shorter startup times, which may be enough to make this worthwhile.  Don't know when I will get to it though.

**Comment by lmmentel** [comment]
Your made some valid comments however let me just add my few cents.

> I want to keep the data in the repo as text. That way I can show users diffs to see what data has changed between versions (source control doesn't work well with binary blobs). It makes it convenient for getting updates from the original sources if I leave it in the original format. 

That's one way to do it, and you could use exactly the same methods to update the db when needed. One way of having a db and still being able to say what's changed would be to document the db value updates for each version. But it you want to keep the data as text I guess a db is out of the question.

> By building the database as part of the installation process I also remove any database migration issues.

In practice migrations do not happen very often, and since your db would be offline they are not very painful.

> Since I will still have the code to process the original data, there is not much maintenance benefit. I hope that using sql would lead to shorter startup times, which may be enough to make this worthwhile. 

From my own experience I can only say that sql saves a lot of maintenance if your database is normalized and can save you from bugs resulting from having redundant data across many files.

**Comment by pkienzle** [comment]
Note security concerns with shipping sqlite listed in https://github.com/pkienzle/periodictable/issues/52#issuecomment-1451362212

**Comment by jrsmith3** [comment]
I had forgotten I even made this request. 😁

It's been nearly a decade since I posted the original issue and I have matured as a developer since then (as has all the tooling). I agree that a text-based format is best for the data.

Feel free to close this issue. Thanks!
